### PR TITLE
Adds "Showing X to Y of Z entries"

### PR DESCRIPTION
**Pull request by enkodellc**
This PR adds a feature to display the specific entries / rows that are being displayed on in the active table. 

class="ng-table-showing"

### CODE REVIEW

**Comment by christianacca** [comment]
Hi enkodellc,

Looked at the pull request myself. I don't have collaborator rights so can't merge myself. I can however offer some code review advice - hope you don't mind!

**I like the idea** of being having the pagination show a message "Showing 11 to 20 or 100 entries"

However there are certain issues I think need to be resolved:

1. I **think** this is the first *text message* to be displayed by the ng-table directive. Text requires you to localize / localise ;-)
2. I'd be wary about adding utility functions like showingMin, to the *ngTableParams factory object*.
  * My concern is that ngTableParams could become a "dumping" ground of utility functions that might not be useful universally to everyone. 
  * That said showingMin and showingMax fns do look useful so I'd probably accept these two.
  * However, I would recommend that maxCount be moved into the ngTablePagination directive as it's very specific to the pagination template.

Also in terms of pull request etiquette I would make the following recommendations:
1. I think your code changes are addressing to things: a feature (pagination message) and a fix (conditionally showing page count buttons). It's good form to split these into two pull requests
2. Code changes should be made to the source files (eg. 06-pagination.js) rather than the distribution files (ng-table.js)

## Localization options

I've done a bit of a work localizing my own angular directives. Now there are quite a few solutions. 

My main criteria for a solution was that it should not **force** someone who wanted to use my directive to take on any third party dependency at *runtime* to a localization library - in my opinion localization is very much an application wide concern and I shouldn't be forcing that decision.

In the end I choose a build time tool that generates *static* html templates, one for each locale. Someone who wants to use my directive can extend the build for my directive to include languages they need to support and have the build produce the html templates to target those language(s).

* [grunt-i18n-template - build time localization tool](https://github.com/rmemoria/grunt-i18n-template)
* [angular-cc-autorefresh - my directive that uses this build tool](https://github.com/christianacca/angular-cc-autorefresh)

**Comment by enkodellc** [comment]
@christianacca thanks for the input. This was one of my first PR's with Github and JS and your response is greatly appreciated. I was looking for this functionality and thought others would want it as well. I will see what I can do about cleaning it up.

**Comment by christianacca** [comment]
Cool and glad you received it so well!

How about re-submitting with some of the advice I mentioned?

If I were in your shoes I would **NOT** be wanting to tackle localization! So how about hard coding English into the pager.html template. *PLUS* make the message optional and by default *not* shown. That way a developer can opt into the message.

If the pull request gets merged, localization can then be tackled as another pull request. If I get write access then to the repo I may then have a bash at implementing localization as a build step (but not promising anything!)

**Comment by enkodellc** [comment]
@christianacca I will not be able to get to the updates anytime too soon. After all it has sat open for 7 months. I am working for more progress on my project that I have this working so that will take priority. If localization is too much then it may be something that gets put in another PR. Thanks again for the input. 

Maybe @iyel or @esvit  can make you a contributor?

**Comment by christianacca** [comment]
No problem Keith and yeah I understand about other priorities...

**Comment by christianacca** [comment]
Closing due to inactivity

**Pull request closed without merging**
