### PR TITLE
Hide redundant Page Size buttons

### PR DESCRIPTION
**Pull request by enkodellc**
Add logic to show only page size if the row count is greater than the count and less than the next count button.

### CODE REVIEW

**Comment by enkodellc** [comment]
Sorry got a typo in my first commit. Either way TravisCI passed but CicleCI didn't? I followed the contribution guidelines.  Not sure what else to do. Admin please let me know.

**Comment by christianacca** [comment]
There some *overlap* between this pull request and https://github.com/esvit/ng-table/pull/656

Lots of good ideas. However, hiding page size buttons is probably not suitable in every situation.

As explained in the the other pull request:
> .. it could be a good time to **consolidate the existing options determining how the pager is displayed**. Once consolidated they would have more "room to grow".

Also, what I think is also important is not to load up on options as this can make it harder to work with the library.

## Alternative solution:

1. make it **easier to create custom pager templates**; *AND/OR*
2. create another template, possibly 2 that will cover the main variations that apps require

**Comment by christianacca** [comment]
There's a pull request to implement infinite scroll (https://github.com/esvit/ng-table/pull/560)

As commented:

> ... separate out pager options and page generation logic from NgTableParams
> ... someone to take the lead on this

**Comment by christianacca** [comment]
So looks like we have a bunch of options for pagination: https://github.com/esvit/ng-table/pull/556, https://github.com/esvit/ng-table/pull/555, https://github.com/esvit/ng-table/pull/648 (this one), https://github.com/esvit/ng-table/pull/656, https://github.com/esvit/ng-table/pull/560, https://github.com/esvit/ng-table/pull/454

**Comment by enkodellc** [comment]
@christianacca  I like your ideas you posted on #656 did you want to assign anyone to start doing those PR's? I am willing to do some work to join these PR's if you are willing to give me some support to get them done to be merged.

**Comment by christianacca** [comment]
Cool. When do you want to start on this? The first thing is to do the consolidation work:

> Pull request 1 - refactor pagination settings (https://github.com/esvit/ng-table/pull/656)

I'll can do a quick peer review and merge. 

If you still got time, we can get onto the enhancements. If you stop there, your contribution will still be of benefit to the project.

C

**Comment by enkodellc** [comment]
Ok I will look into the refactor for the pagination settings. Should I refactor for the current settings to start and then do additional PR's when adding features or should I include some of those settings right off the get go.

**Comment by christianacca** [comment]
Let's keep the refactoring into a separate PR

**Comment by enkodellc** [comment]
I just submitted a separate PR. #674

**Comment by christianacca** [comment]
Yup, just merging it with some stuff I've just pushed. Also, I'm got a couple of small feedback items around the commit

**Pull request closed without merging**
