### PR TITLE
Changed 'filter-data' to accept function/array/object variables

### PR DESCRIPTION
**Pull request by israelidanny**
This comes very useful when dealing with autocomplete inputs that need to pull data from the server. For instance, the following example deals with twitter's typeahead.

We define a new template:
```javascript
$templateCache.put('ng-table/filters/typeahead.html', '<input type="text" class="sfTypeahead filter filter-typeahead" name="{{column.filterName}}" options="{highlight: true}" datasets="column.data" ng-model="params.filter()[name]">');
```

In this case, filter.data would have had to look like this, to be able to pull stuff from the server:
```
{
    displayKey: 'val',
    source: workplaces.ttAdapter()
}
```

This pull request allows for that without prohibiting the usual way of doing things.

### CODE REVIEW

**Comment by lukad** [comment]
+1

**Comment by iyel** [comment]
please provide an example where it will suite

**Comment by israelidanny** [comment]
I provided a valid use case (used in a production app of mine) and an example in the pull request comments

**Comment by avneeshroks** [comment]
Hey Guys, can anyone please help me solving my problem related to filter-data update i have mentioned over here - https://github.com/esvit/ng-table/issues/186#issuecomment-113142191

**Pull request closed without merging**
