### PR TITLE
Issue 602 add a column on the fly dynamic table

### PR DESCRIPTION
**Pull request by jlebleu**
Testing table header creation
Small example

### CODE REVIEW

**Comment by christianacca** [comment]
Hey Jean-Yves, sorry for not getting back sooner.

Pull request looks good. One last thing can you amend your commit message so that it reads:

> feat(ngTableDynamic): add a column on the fly

I'll then merge this.
C

**Comment by jlebleu** [comment]
I noticed today that 

     controller.loadFilterData(scope.$columns);

 in the watch function is missing, need to amend the test to to prove that filterdata is not loaded, what do you think ?

**Comment by christianacca** [comment]
Two things:

1. I think the code changes can be tidied up a bit
2. New columns added on the fly need their filter data loaded (as you already pointed out)

Below is code that I think accommodates both issues.

As it stands the code below is inefficient. An improvement that could be made is to only call `controller.loadFilterData` with the new columns being added.

**Can you**:
1. use the code below 
2. add any additional test you were thinking
3. if you have the appetite: optimize things so that `controller.loadFilterData` is called only with the new columns being added
4. commit the changes
5. [squish](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the commits into one with the commit msg: *feat(ngTableDynamic): add a column on the fly*

````
return function (scope, element, attrs, controller) {
    var expr = parseDirectiveExpression(attrs.ngTableDynamic);

    controller.setupBindingsToInternalScope(expr.tableParams);
    controller.compileDirectiveTemplates();

    scope.$watchCollection(expr.columns, function (newCols/*, oldCols*/) {
        scope.$columns = controller.buildColumns(newCols || []);
        controller.loadFilterData(scope.$columns);
    });
};
````

**Comment by christianacca** [comment]
Merged by https://github.com/esvit/ng-table/commit/016827745bd618aeafc16f4deaa855b29452626a

**Pull request closed without merging**
