### PR TITLE
Possibility to define placeholder for text field filter. See example 29.

### PR DESCRIPTION
**Pull request by gordensh**
If are you going to define a filter, sometimes is good idea to show placeholder for this field.
Especially if you have compound filter:
placeholder

### CODE REVIEW

**Comment by takeit** [comment]
+1

**Comment by whroman** [comment]
+1

**Comment by haolinj** [comment]
+1

**Comment by akashrajkn** [comment]
+1

**Comment by christianacca** [comment]
https://github.com/esvit/ng-table/commit/275f1c88f46515415a43e434a65fe54b4d813637 add this feature

**Pull request closed without merging**
