### PR TITLE
Fix(header.html): sort icon appears twice using custom header template

### PR DESCRIPTION
**Pull request by christianacca**
The template for header cell causes the sort icon to appear twice when a custom header template is requested (eg data-header='myColumnHeader.html').

The header template introduces a redudant nested div in the case of a custom header template. This extra div is then targed by a css descendant selector that adds the sort icon.

This fix removes the redundant div thus avoiding the css issue.

### CODE REVIEW

**Comment by iyel** [comment]
Merged

**Comment by iyel** [comment]
@christianacca could you also add examples for your PRs, please?

**Comment by christianacca** [comment]
Hi iyel,

I'm going to create some official examples this morning (examples/demoxx.html). I'll create another pull request for them if that's ok?

Christian

**Comment by iyel** [comment]
Hi @christianacca,
yes for sure

**Comment by christianacca** [comment]
I have created a pull request for adding these as "official" examples: https://github.com/esvit/ng-table/pull/503

**Pull request closed without merging**
