### PR TITLE
Initialize $data from settings.data

### PR DESCRIPTION
**Pull request by juracy**

### CODE REVIEW

**Comment by christianacca** [comment]
Hi Juracy,

Thanks for contribution.

The change you're suggesting actually isn't a good fit for `ngTable`. That's because the `$scope.data` and `settings().data` are intended for two different purposes.

You can think of `settings().data` as the **entire dataset** that `ngTable` has been made responsible for managing.

Whereas `$scope.data` is for the current page worth of data that is being displayed to the user.

I'm seriously considering renaming `settings().data` to `settings().dataset` to better clarify the intent.

C

**Comment by juracy** [comment]
Hi Christian, I'm working on a padding option for ng-table.

That's useful for keeping the same height (and appearance) between pages, even at the last one. But at slow connections (for ajax) the first page starts with $data empty, therefore the rows are not rendered !

I was looking for a option to fill $scope.$data at first moment, even before getData.

Do you have any idea ?

**Comment by christianacca** [comment]
Mmm... well in theory you could provide the NgTableParams with an initial
array containing the number of rows you want to pad.

So something like:

`var tableParams = new NgTableParams({...}, { data: paddingDataset });`

Haven't tested so might not give what you need... let me know how you get
on :-)

C

**Comment by juracy** [comment]
Well, that code works only with my patch !

settings.data -> $scope.$data

**Comment by christianacca** [comment]
YEAH I feel really silly. Just righting a better reply. Hold on :-)

**Comment by christianacca** [comment]
OK, so my suggestion won't work!

You might have to do something "special" (read hack) in your `getData` function. Maybe the `getData` function would return `settings().data` if it sees it there and then trigger the real ajax request.

Something like:

```js
function getData($defer, params) {
    if (params.settings().data) {
        $defer.resolve(params.settings().data);
        params.settings({ data: null });
        params.reload();
    }
}
```

**Comment by christianacca** [comment]
Or another (better) way:

```html
<tr ng-repeat="row in rows = ($data.length ? $data : paddingRows)"
```

**Comment by christianacca** [comment]
Here's a jsfiddle with the basic idea: http://jsfiddle.net/christianacca/9bqc3uyv/

**Comment by juracy** [comment]
I get it, but don't you think that it will be a nice feature to ng-table ?

We can use another name, like initialData ! And enhance the implementation, applying initialData only once, while $data is null !

**Comment by christianacca** [comment]
More !== better.

I think less options in a library often produces be a better design. Take for example the options for creating an directive - the large number of options have been cited as one of the reason why authoring directives is intimidating.

So as there is a simple alternative for maintaining padding then I don't want to accept this update to the library.

C

**Pull request closed without merging**
