### PR TITLE
Update release process to automatically also release on NPM

### LINKED ISSUE #731: Update npm with most recent module versions
The most recent module versions are not downloadable via npm. Please provide them!

### PR DESCRIPTION
**Pull request by astik**
Should fix #731 and #683.

### CODE REVIEW

**Comment by astik** [comment]
Tests are failing but i didn't change anything to the basecode.

@esvit any chance to have this merged and used soon ?
This will allow us to use ng-table without bower =P

**Comment by ccrowhurstram** [comment]
Hi @astik,

I don't think step 1 "update version number" can be dropped. You see step 1 in the process ensures that the minifed files created in step 2 has the new version number.

Also, what permissions are required in order to push to push to npm? I don't think I have them myself...

C

**Comment by astik** [comment]
@ccrowhurstram I agree for the version part, but is it really necessary ? I mean, a lot of people now use a package manager so that we know which version is used through package.json or bower.json.

Still, if you want, there is an option "bump" to disable automatic version change. That way, I can reset the first step by leaving the version setting manual.

To publish, I think you only need write access on the github project ...

**Comment by astik** [comment]
Here some tests.

Without specific settings :

```
$ grunt release --no-write
Running "release" task
>> Release dry run.
>> bumped version of bower.json to 1.0.0
>> bumped version of package.json to 1.0.0
>> staged bower.json package.json
>> Committed all files
>> created new git tag: v1.0.0
>> pushed to remote
>> pushed new tag 1.0.0 to remote
>> published version 1.0.0 to npm
```

After disabling bump, add and commit :
```
$ grunt release --no-write
Running "release" task
>> Release dry run.
>> created new git tag: v1.0.0-beta.9
>> pushed to remote
>> pushed new tag 1.0.0-beta.9 to remote
>> published version 1.0.0-beta.9 to npm
``` 

Would that be OK for you ?

**Comment by ccrowhurstram** [comment]
"I mean, a lot of people now use a package manager so that we know which version is used through package.json or bower.json"

You're right!

Here's my preference:
1. disable automatic version change for the time being (this PR)
2. create another PR that removes the version number from the minified files and then renable the automatic version change

Can you do this @astik?

C

**Comment by astik** [comment]
@ccrowhurstram modification has been pushed.

To be honest, I remove the version handling to ease up your work =)
If you want to keep the version in the generated file, there is no problem with that =P

As you can see with the latest commit, this is only a question of 3 attributes in the release plugin, so when you'll want to remove the version, simply remove those 3 attributes.

**Comment by ccrowhurstram** [comment]
Cool.

I'll try it out tonight.

@astik, are you familar with using git to [squashing](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the commits in you PR? If so can you do this. If not I'll do this when I merge the commit.

C

**Comment by astik** [comment]
New day, new thing to learn !
Thanks for making me learn this, I wasn't familiar with squashing =P

**Comment by ccrowhurstram** [comment]
Cool :-)

**Comment by kyrylkov** [comment]
So could you go ahead with this and publish to NPM?

**Comment by astik** [comment]
@ccrowhurstram any news on releasing ngTable on NPM ?

**Comment by christianacca** [comment]
Ok so I feel terrible about holding this up.

What I want to do is get the type definition file correct with regard to
npm. The new typings project have changed where type definition files are
maintained. Now they are delivered with the main npm package. I think also
that the way that the type definitions are written might have changed as
well.

What I want to do make sure to get the typing file right and then deploy to
npm.

On a positive, I have already written the type definition file at least for
the old way of doing it and indeed this is already published to the
(legacy) definitely typed registry.

I don't know how to speed things up here as obviously I'm a bottleneck
here...

Is someone in the community could look into the typings and make the
necessary changes would be of course one option...

C

**Comment by astik** [comment]
To be honest, I have no idea of what you're talking about =D
What is the "type definition file" ?

**Comment by christianacca** [comment]
:-)

A type definition file feeds the typescript compiler with the necessary
type annotations that are missing from plain JS.

Typically this becomes important if the app your writing (that uses
ng-table) is being written in typescript. Although there are other uses for
this typing file like being able to generate reference documentation for
the ng-table API.

Here's the one I created for ng-table:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/ng-table/ng-table.d.ts

**Comment by astik** [comment]
Ok, thanks for the explanation, I was searching something that wasn't about TS =P

**Comment by ccrowhurstram** [comment]
no probs

**Comment by astik** [comment]
Hi @ccrowhurstram, it's been a while since last message, any news about this pull request ?

I manage to do some change like updating karma dependencies and add some configuration for travis and circle in order to make them work.
Now all test indicators are green =)

**Comment by ccrowhurstram** [comment]
## Here's what I've done / doing:

* I've ask @esvit for permissions to publish to npm
* I've cleaned up what gets published to npm
* I've made angular a peer dependency as this is now the recommended practice (see [ng-conf-library](https://github.com/ocombe/ng-conf-library#user-content-1-init-the-project))
* I've used your changes to fix circle-ci build, update karama and fix the bower warning (thank you!)
* I've looked at the grunt release plugin and I'm not convinced (explanation below)

## Grunt release plugin - cons

I can't see it saving many steps in the end. 

You still will need to:
* generate the changelog.md, 
* create a release in github so as to add changelog text
* commit changelog.md and dist folder. 

Also I worry about support issues when a contributor runs the grunt task and their git credentials are not resolved from a git credential store on their machine, or trying to setup global environment variables to use these as credentials instead.

It feels that real benefit would be had only if the plugin could be included in a custom grunt task. The end result being:
* the changelog.md automatically generated
* the dist and changelog.md files were committed in the same commit as the pacakge.json and bower.json
* the release tag created with the same changelog text

Event then I suspect git credentials would be a pain to resolve for some collaborators, but the benefit would be more than the cost at that point.

**Comment by christianacca** [comment]
I'm closing this now but thanks for your help Romain getting there.

Once @esvit gives me permissions I'll publish to npm

**Comment by astik** [comment]
@ccrowhurstram, I would have appreciate you differentiated the author and the commiter for ed49adb and 540d5c1.
Anyway, the most import is the code being consolidated no matter what =)

**Comment by ccrowhurstram** [comment]
I hear you. Sorry about that, and again thanks Romain.

**Pull request closed without merging**
